#!/bin/sh

# Run from this directory
cd ${0%/*} || exit 1    

# Source run functions:
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Splitting domain for parallel solving:
runApplication decomposePar

# Create the AD locations in the domain:
runParallel topoSet

# Solve the flow
runParallel $(getApplication)

# Reconstruction (needed for parallel runs):
runApplication reconstructParMesh -constant
runApplication reconstructPar -constant

# Saving some files:
runApplication foamLog log.simpleFoam

# Making a .foam-file, which can be used to load results to Paraview.
runApplication touch test.foam

# Some postprocess work
#runApplication postProcess -func lines -latestTime
#mv log.postProcess log.postProcesslines


#------------------------------------------------------------------------------
